front_page:
    path: /
    controller: App\Controller\FrontPageController::index

test_mailer:
    path: /test/mailer
    controller: App\Controller\TestController::mailer

debug_phpinfo:
    path: /debug/phpinfo
    controller: App\Controller\DebugController::phpinfo

debug_vars:
    path: /debug/vars
    controller: App\Controller\DebugController::vars
